import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/env/index.ts',
    'src/http/index.ts',
    'src/sentry/index.ts',
    'src/logging/index.ts',
    'src/cls/index.ts',
    'src/validation/index.ts',
    'src/database/index.ts',
    'src/database/migrate.ts',
    'src/swagger/index.ts',
    'src/config/vitest.ts',
    'src/config/eslint.ts',
    'src/testing/index.ts',
    'src/testing/setup.ts',
  ],
  format: ['cjs'],
  dts: true,
  clean: true,
  splitting: false,
  external: [
    /^@nestjs/,
    /^@mikro-orm/,
    /^@sentry/,
    /^nestjs-/,
    /^pino/,
    /^vitest/,
    /^unplugin-swc/,
    /^typescript-eslint/,
    /^eslint/,
    /^@eslint/,
    /^globals/,
    'reflect-metadata',
    'rxjs',
    'dotenv',
  ],
});
